### ISSUE TITLE
Multi-channel support

### ISSUE THREAD

**Issue by dotnetslash** [aelse/slackard#11]
I have a branch that supports listening to multiple channels. Do I need write-access to set up a pull request? Alternatively, I've attached a patch.

[multi-channel.patch.txt](https://github.com/aelse/slackard/files/598110/multi-channel.patch.txt)

**Comment by aelse** [comment]
Hi, if you've cloned to your own repo on GH you should be able to submit a PR.

**Comment by dotnetslash** [comment]
Doh! I haven't but I will when I get some free time. Thanks.

**Comment by dotnetslash** [comment]
Pull request submitted. Thanks for the help.
